server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/aldanedev/bootcamp
          search-paths: configdata
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  security:
      user:
        name: root
        password: root   
  application:
    name: config-services     